<?php

namespace Cgonser\SwiftMailerDatabaseS3SpoolBundle\Repository;

/**
 * MailQueueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailQueueRepository extends \Doctrine\ORM\EntityRepository
{
}
